spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/realworld
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  file.name: ./log/backend.log
  level:
    root: INFO
    com.sakrafux.sem.realworld.logging: DEBUG
  pattern:
    level: r=%X{r} ip=%X{ip} u=%X{u} %5p