spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/realworld
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: false