spring:
  config:
    import: optional:classpath:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false

appl:
  google:
    client-id: ${GOOGLE_CLIENT_ID}