spring:
  config:
    import: optional:classpath:.env[.properties]
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

appl:
  google:
    client-id: ${GOOGLE_CLIENT_ID}